// Weekly & Monthly Ledger View
// Shows aggregated impact data over time

import { useState } from 'react';
import { Calendar, TrendingUp, TrendingDown, Download, Share2, ChevronLeft, ChevronRight, QrCode } from 'lucide-react';
import type { DaySession, ActivityLog } from '@/types';
import { aggregateWeeklyLedger, aggregateMonthlyLedger, formatLedgerForExport, generateShareCard, type LedgerPeriod } from '@/lib/ledgerEngine';
import { useScrollAnimation } from '@/hooks/useScrollAnimation';

interface LedgerViewProps {
  daySessions: DaySession[];
  activities: ActivityLog[];
  onOpenQR?: () => void;
}

export function LedgerView({ daySessions, activities, onOpenQR }: LedgerViewProps) {
  const [viewMode, setViewMode] = useState<'week' | 'month'>('week');
  const { ref, isVisible } = useScrollAnimation<HTMLDivElement>({ threshold: 0.1 });

  // Generate ledger based on view mode
  const ledger: LedgerPeriod = viewMode === 'week'
    ? aggregateWeeklyLedger(daySessions, activities)
    : aggregateMonthlyLedger(daySessions, activities);

  const handleExport = () => {
    const report = formatLedgerForExport(ledger);
    // Export as styled HTML
    const htmlReport = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>GreenPulse ${ledger.periodType} Report</title>
<style>body{font-family:system-ui,sans-serif;max-width:700px;margin:0 auto;padding:2rem;color:#1a1a1a}
.header{text-align:center;padding:1.5rem;background:linear-gradient(135deg,#22C55E20,#16A34A20);border-radius:1rem;margin-bottom:2rem}
.header h1{color:#22C55E;margin:0}.stat-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem;margin:1.5rem 0}
.stat{background:#f9fafb;padding:1rem;border-radius:.75rem;text-align:center}.stat .value{font-size:1.5rem;font-weight:700}
.stat .label{font-size:.75rem;color:#6b7280}.pre{white-space:pre-wrap;background:#f3f4f6;padding:1.5rem;border-radius:.75rem;font-size:.875rem;line-height:1.6}
</style></head><body>
<div class="header"><h1>🌿 GreenPulse</h1><p>${ledger.periodType.charAt(0).toUpperCase() + ledger.periodType.slice(1)} Report · ${ledger.startDate} → ${ledger.endDate}</p></div>
<div class="stat-grid">
<div class="stat"><div class="value">${Math.round(ledger.averageDailyScore)}</div><div class="label">Avg Score</div></div>
<div class="stat"><div class="value">${ledger.totalCo2eKg.toFixed(2)} kg</div><div class="label">CO₂e Emitted</div></div>
<div class="stat"><div class="value">${ledger.totalAvoidedCo2eKg.toFixed(2)} kg</div><div class="label">CO₂e Avoided</div></div>
<div class="stat"><div class="value">${ledger.totalGreenPoints}</div><div class="label">Green Points</div></div>
</div>
<pre class="pre">${report}</pre>
<p style="text-align:center;color:#9ca3af;font-size:.75rem;margin-top:2rem">Generated by GreenPulse · ${new Date().toLocaleString()}</p>
</body></html>`;

    const blob = new Blob([htmlReport], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `greenpulse-${ledger.periodType}-${ledger.startDate}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    const shareData = generateShareCard(ledger);
    const shareText = `${shareData.headline}\n\n${shareData.stats.join('\n')}\n\n#GreenPulse`;

    if (navigator.share) {
      navigator.share({
        title: `My ${ledger.periodType} Sustainability Impact`,
        text: shareText,
      }).catch(() => {});
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(shareText).then(() => {
        alert('Report copied to clipboard!');
      }).catch(() => {
        prompt('Copy this report:', shareText);
      });
    }
  };

  // Calculate net impact
  const netImpact = ledger.totalCo2eKg - ledger.totalAvoidedCo2eKg;
  const hasPositiveImpact = ledger.totalAvoidedCo2eKg > ledger.totalCo2eKg * 0.2;

  return (
    <section className="w-full bg-[#F6F8F6] py-16">
      <div ref={ref} className="max-w-6xl mx-auto px-6">
        {/* Header */}
        <div 
          className={`text-center mb-8 transition-all duration-700 ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
          }`}
        >
          <div className="inline-flex items-center justify-center w-16 h-16 bg-[#22C55E] rounded-full mb-4">
            <Calendar className="w-8 h-8 text-white" />
          </div>
          <h2 className="text-3xl font-bold text-gray-900 mb-2">Impact Ledger</h2>
          <p className="text-gray-600">Your personal sustainability statement</p>
        </div>

        {/* View Toggle */}
        <div 
          className={`flex justify-center gap-3 mb-8 transition-all duration-700 delay-100 ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
          }`}
        >
          <button
            onClick={() => setViewMode('week')}
            className={`px-6 py-2.5 rounded-xl font-medium transition-all ${
              viewMode === 'week'
                ? 'bg-[#22C55E] text-white'
                : 'bg-white text-gray-600 hover:bg-gray-50'
            }`}
          >
            Weekly
          </button>
          <button
            onClick={() => setViewMode('month')}
            className={`px-6 py-2.5 rounded-xl font-medium transition-all ${
              viewMode === 'month'
                ? 'bg-[#22C55E] text-white'
                : 'bg-white text-gray-600 hover:bg-gray-50'
            }`}
          >
            Monthly
          </button>
        </div>

        {/* Period Info */}
        <div 
          className={`gp-card p-6 mb-6 transition-all duration-700 delay-200 ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
          }`}
        >
          <div className="flex items-center justify-between mb-6">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-1">
                {ledger.startDate} → {ledger.endDate}
              </h3>
              <p className="text-sm text-gray-600">
                {ledger.daysTracked} days tracked
              </p>
            </div>
            <div className="flex gap-2">
              <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <ChevronLeft className="w-5 h-5 text-gray-600" />
              </button>
              <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <ChevronRight className="w-5 h-5 text-gray-600" />
              </button>
            </div>
          </div>

          {/* Net Impact Banner */}
          <div className={`p-4 rounded-xl mb-6 ${
            hasPositiveImpact 
              ? 'bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200' 
              : 'bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200'
          }`}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                {hasPositiveImpact ? (
                  <TrendingDown className="w-6 h-6 text-green-600" />
                ) : (
                  <TrendingUp className="w-6 h-6 text-blue-600" />
                )}
                <div>
                  <p className="text-sm text-gray-600">Net CO₂e Impact</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {netImpact.toFixed(2)} kg
                  </p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-600">Avoided</p>
                <p className="text-xl font-bold text-green-600">
                  -{ledger.totalAvoidedCo2eKg.toFixed(2)} kg
                </p>
              </div>
            </div>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="p-4 bg-white rounded-xl border border-gray-200">
              <p className="text-xs text-gray-500 mb-1">Avg Score</p>
              <p className="text-2xl font-bold text-gray-900">
                {Math.round(ledger.averageDailyScore)}
              </p>
              <p className="text-xs text-gray-400">/100</p>
            </div>
            <div className="p-4 bg-white rounded-xl border border-gray-200">
              <p className="text-xs text-gray-500 mb-1">Energy</p>
              <p className="text-2xl font-bold text-gray-900">
                {ledger.totalKwh.toFixed(1)}
              </p>
              <p className="text-xs text-gray-400">kWh</p>
            </div>
            <div className="p-4 bg-white rounded-xl border border-gray-200">
              <p className="text-xs text-gray-500 mb-1">Water</p>
              <p className="text-2xl font-bold text-gray-900">
                {ledger.totalWaterLiters}
              </p>
              <p className="text-xs text-gray-400">L</p>
            </div>
            <div className="p-4 bg-white rounded-xl border border-gray-200">
              <p className="text-xs text-gray-500 mb-1">Points</p>
              <p className="text-2xl font-bold text-gray-900">
                {ledger.totalGreenPoints}
              </p>
              <p className="text-xs text-gray-400">earned</p>
            </div>
          </div>
        </div>

        {/* Top Categories */}
        {ledger.topCategories.length > 0 && (
          <div 
            className={`gp-card p-6 mb-6 transition-all duration-700 delay-300 ${
              isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
            }`}
          >
            <h3 className="font-semibold text-gray-900 mb-4">Top Impact Categories</h3>
            <div className="space-y-4">
              {ledger.topCategories.map((category, index) => (
                <div key={category.category}>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white ${
                        index === 0 ? 'bg-amber-500' : index === 1 ? 'bg-gray-400' : 'bg-orange-400'
                      }`}>
                        {index + 1}
                      </span>
                      <span className="text-sm capitalize font-medium text-gray-700">
                        {category.category}
                      </span>
                      <span className="text-xs text-gray-500">
                        ({category.activityCount} activities)
                      </span>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-bold text-gray-900">
                        {category.co2eKg.toFixed(2)} kg
                      </p>
                      <p className="text-xs text-gray-500">
                        {category.percentage.toFixed(0)}%
                      </p>
                    </div>
                  </div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-[#22C55E] to-emerald-400 rounded-full transition-all duration-1000"
                      style={{ width: isVisible ? `${category.percentage}%` : '0%' }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Daily Trend */}
        {ledger.dailyTrend.length > 0 && (
          <div 
            className={`gp-card p-6 mb-6 transition-all duration-700 delay-400 ${
              isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
            }`}
          >
            <h3 className="font-semibold text-gray-900 mb-4">Daily Trend</h3>
            <div className="space-y-2 max-h-64 overflow-y-auto">
              {ledger.dailyTrend.map((day) => (
                <div 
                  key={day.date}
                  className="flex items-center gap-4 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <span className="text-xs font-medium text-gray-500 w-20">
                    {new Date(day.date).toLocaleDateString('en', { month: 'short', day: 'numeric' })}
                  </span>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <div className="flex-1 h-2 bg-gray-200 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-[#22C55E] rounded-full transition-all duration-500"
                          style={{ width: `${Math.min((day.score / 100) * 100, 100)}%` }}
                        />
                      </div>
                      <span className="text-xs font-medium text-gray-700 w-8">
                        {day.score}
                      </span>
                    </div>
                    <div className="flex items-center gap-3 text-xs text-gray-500">
                      <span>{day.co2eKg.toFixed(2)} kg</span>
                      <span className="text-green-600">-{day.avoidedCo2eKg.toFixed(2)} kg</span>
                      <span className="text-amber-600">{day.greenPoints} pts</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div 
          className={`flex gap-3 transition-all duration-700 delay-500 ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'
          }`}
        >
          <button
            onClick={handleShare}
            className="flex-1 py-3 px-4 rounded-xl border-2 border-[#22C55E] text-[#22C55E] font-medium hover:bg-[#22C55E]/10 transition-all flex items-center justify-center gap-2"
          >
            <Share2 className="w-5 h-5" />
            Share
          </button>
          <button
            onClick={handleExport}
            className="flex-1 py-3 px-4 rounded-xl bg-[#22C55E] text-white font-medium hover:bg-[#16A34A] transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" />
            Export
          </button>
          {onOpenQR && (
            <button
              onClick={onOpenQR}
              className="flex-1 py-3 px-4 rounded-xl bg-gray-900 text-white font-medium hover:bg-gray-800 transition-all flex items-center justify-center gap-2"
            >
              <QrCode className="w-5 h-5" />
              QR Code
            </button>
          )}
        </div>

        {/* Empty State */}
        {ledger.daysTracked === 0 && (
          <div className="text-center py-12">
            <Calendar className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-700 mb-2">No Data Yet</h3>
            <p className="text-gray-500 text-sm">
              Start logging activities to see your impact over time
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
